# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Observables' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Observables
  pod 'RxSwift'
  pod 'RxCocoa'
 
  target 'ObservablesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObservablesUITests' do
    # Pods for testing
  end

end
